[package]
name = "interp"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
ast = { path = "../ast" }
value = { path = "../value" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
